# This is a basic workflow to help you get started with Actions

name: Python package test

on: 
  push:
    branches:
      - main

jobs:
  ubuntu:
    name: package on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name : checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Build Python Package
        run: python setup.py sdist bdist_wheel  # Replace with your build command

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: test_package
          path: ./dist/*.whl

      - name: Download and Install Package
        run: |
            mkdir -p ~/.pip
            echo -e "[global]\nextra-index-url=https://pypi.org/simple" >> ~/.pip/pip.conf
            pip install https://api.github.com/repos/tarungurjar11/github_action_1/actions/artifacts/942494283/zip
          # https://github.com/tarungurjar11/github_action_1/releases/latest/download/test_package-0.1.0-py3-none-any.whl
        env:
            username: tarungurjar11
            repository: github_action_1
            package-name: test_package-0.1.0-py3-none-any
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: python -m test.py

# https://api.github.com/repos/tarungurjar11/github_action_1/actions/artifacts