# This is a basic workflow to help you get started with Actions

name: I am New


on: 
  push:
    branches:
      - main

jobs:
  job1:
    name: JOB 1
    runs-on: ubunto-latest
    steps:
      - name : step one
        uses: actions/checkout@v2
      - name : step two
        run: |
          echo Hello, world!
          env | sort
  job2:
    name: JOB 2
    runs-on: windows-latest
    steps:
      - name : step one
        uses: actions/checkout@v2
