# This is a basic workflow to help you get started with Actions

name: Python package test

on: 
  push:
    branches:
      - main

jobs:
  ubuntu:
    name: package on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name : checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Build Python Package
        run: python setup.py sdist bdist_wheel  # Replace with your build command

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: test_package
          path: ./dist/

      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
          
      - name: Download and Install Package
        run: |
          mkdir -p ~/.pip
          echo -e "[global]\nextra-index-url=https://pypi.org/simple" >> ~/.pip/pip.conf
          pip install https://github.com/tarungurjar11/github_actions_1/releases/latest/download/test_package.whl
        env:
          username: tarungurjar11
          repository: github_actions_1
          package-name: test_package
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # test-ubuntu:
  #   name: package testing on ubuntu
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name : checkout repo
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9  # Replace with your desired Python version
      
      # - name: Install Dependencies
      #   run: |
      #     pip install -r requirements.txt
      
      # - name: Build Python Package
      #   run: python setup.py sdist bdist_wheel  # Replace with your build command

      # - name: Run Tests
      #   run: |
      #     # Run your tests here
      #     # For example:
      #     # python -m unittest discover tests